package application.rest;

import javax.annotation.security.DeclareRoles;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

import org.eclipse.microprofile.auth.LoginConfig;
import org.eclipse.microprofile.openapi.annotations.Components;
import org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition;
import org.eclipse.microprofile.openapi.annotations.enums.SecuritySchemeIn;
import org.eclipse.microprofile.openapi.annotations.enums.SecuritySchemeType;
import org.eclipse.microprofile.openapi.annotations.info.Info;
import org.eclipse.microprofile.openapi.annotations.media.ExampleObject;
import org.eclipse.microprofile.openapi.annotations.security.SecurityScheme;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

@ApplicationPath("/")

@LoginConfig(authMethod = "MP-JWT", realmName = "jwt-jaspi")
@DeclareRoles({ "user" })

@OpenAPIDefinition(
        info = @Info(
                title = "RealWorld example app REST endpoints", 
                version = "1.0", 
                description = "An OpenLiberty implementation of the RealWorld API Spec using MicroProfile: https://github.com/gothinkster/realworld/tree/master/api"), 
        components = @Components(
                securitySchemes = {
                        @SecurityScheme(securitySchemeName = "Authentication", type = SecuritySchemeType.APIKEY, apiKeyName = "Authorization", in = SecuritySchemeIn.HEADER, description = "Enter a valid token, generated by creating a user or logging in, to make requests which require authentication. Enter as: Token jwt.token.here") 
                        },
                examples = {
                        @ExampleObject(name = "User_authentication", value = ""
                                + "{\n"
                                + "  \"user\":{\n"
                                + "    \"email\": \"jake@jake.jake\",\n"
                                + "    \"password\": \"jakejake\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "User_registration", value = ""
                                + "{\n"
                                + "  \"user\":{\n"
                                + "    \"username\": \"jake\",\n"
                                + "    \"email\": \"jake@jake.jake\",\n"
                                + "    \"password\": \"jakejake\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "User_update", value = ""
                                + "{\n"
                                + "  \"user\":{\n"
                                + "    \"email\": \"jake@jake.jake\",\n"
                                + "    \"bio\": \"I like to skateboard\",\n"
                                + "    \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Article_create", value = ""
                                + "{\n"
                                + "  \"article\": {\n"
                                + "    \"title\": \"How to train your dragon\",\n"
                                + "    \"description\": \"Ever wonder how?\",\n"
                                + "    \"body\": \"You have to believe\",\n"
                                + "    \"tagList\": [\"reactjs\", \"angularjs\", \"dragons\"]\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Article_update", value = ""
                                + "{\n"
                                + "  \"article\": {\n"
                                + "    \"title\": \"Did you train your dragon?\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Comment_create", value = ""
                                + "{\n"
                                + "  \"comment\": {\n"
                                + "    \"body\": \"His name was my name too.\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "User_returned", value = ""
                                + "{\n"
                                + "  \"user\": {\n"
                                + "    \"email\": \"jake@jake.jake\",\n"
                                + "    \"token\": \"jwt.token.here\",\n"
                                + "    \"username\": \"jake\",\n"
                                + "    \"bio\": null,\n"
                                + "    \"image\": null\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "User_updated_returned", value = ""
                                + "{\n"
                                + "  \"user\": {\n"
                                + "    \"email\": \"jake@jake.jake\",\n"
                                + "    \"token\": \"jwt.token.here\",\n"
                                + "    \"username\": \"jake\",\n"
                                + "    \"bio\": \"I like to skateboard\",\n"
                                + "    \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\"\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Profile_returned", value = ""
                                + "{\n"
                                + "  \"profile\": {\n"
                                + "    \"username\": \"jake\",\n"
                                + "    \"bio\": \"I work at statefarm\",\n"
                                + "    \"image\": \"https://static.productionready.io/images/smiley-cyrus.jpg\"\n"
                                + "    \"following\": false\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Profile_following_returned", value = ""
                                + "{\n"
                                + "  \"profile\": {\n"
                                + "    \"username\": \"jake\",\n"
                                + "    \"bio\": \"I work at statefarm\",\n"
                                + "    \"image\": \"https://static.productionready.io/images/smiley-cyrus.jpg\"\n"
                                + "    \"following\": true\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Article_returned", value = ""
                                + "{\n"
                                + "  \"article\": {\n"
                                + "    \"slug\": \"how-to-train-your-dragon\",\n"
                                + "    \"title\": \"How to train your dragon\",\n"
                                + "    \"description\": \"Ever wonder how?\",\n"
                                + "    \"body\": \"It takes a Jacobian\",\n"
                                + "    \"tagList\": [\"dragons\", \"training\"],\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
                                + "    \"favorited\": false,\n"
                                + "    \"favoritesCount\": 0,\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Article_favourited_returned", value = ""
                                + "{\n"
                                + "  \"article\": {\n"
                                + "    \"slug\": \"how-to-train-your-dragon\",\n"
                                + "    \"title\": \"How to train your dragon\",\n"
                                + "    \"description\": \"Ever wonder how?\",\n"
                                + "    \"body\": \"It takes a Jacobian\",\n"
                                + "    \"tagList\": [\"dragons\", \"training\"],\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
                                + "    \"favorited\": true,\n"
                                + "    \"favoritesCount\": 0,\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Articles_returned", value = ""
                                + "{\n"
                                + "  \"articles\":[{\n"
                                + "    \"slug\": \"how-to-train-your-dragon\",\n"
                                + "    \"title\": \"How to train your dragon\",\n"
                                + "    \"description\": \"Ever wonder how?\",\n"
                                + "    \"body\": \"It takes a Jacobian\",\n"
                                + "    \"tagList\": [\"dragons\", \"training\"],\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
                                + "    \"favorited\": false,\n"
                                + "    \"favoritesCount\": 0,\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }, {\n"
                                + "    \"slug\": \"how-to-train-your-dragon-2\",\n"
                                + "    \"title\": \"How to train your dragon 2\",\n"
                                + "    \"description\": \"So toothless\",\n"
                                + "    \"body\": \"It a dragon\",\n"
                                + "    \"tagList\": [\"dragons\", \"training\"],\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
                                + "    \"favorited\": false,\n"
                                + "    \"favoritesCount\": 0,\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }],\n"
                                + "  \"articlesCount\": 2\n"
                                + "}"),
                        @ExampleObject(name = "Comment_returned", value = ""
                                + "{\n"
                                + "  \"comment\": {\n"
                                + "    \"id\": 1,\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"body\": \"It takes a Jacobian\",\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }\n"
                                + "}"),
                        @ExampleObject(name = "Comments_returned", value = ""
                                + "{\n"
                                + "  \"comments\": [{\n"
                                + "    \"id\": 1,\n"
                                + "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"updatedAt\": \"2016-02-18T03:22:56.637Z\",\n"
                                + "    \"body\": \"It takes a Jacobian\",\n"
                                + "    \"author\": {\n"
                                + "      \"username\": \"jake\",\n"
                                + "      \"bio\": \"I work at statefarm\",\n"
                                + "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
                                + "      \"following\": false\n"
                                + "    }\n"
                                + "  }]\n"
                                + "}"),
                        @ExampleObject(name = "Tags_returned", value = ""
                                + "{\n"
                                + "  \"tags\": [\n"
                                + "    \"reactjs\",\n"
                                + "    \"angularjs\"\n"
                                + "  ]\n"
                                + "}")
                }), tags = {
                        @Tag(name = "Login", description = "Endpoints for registration and authentication"),
                        @Tag(name = "User", description = "Endpoints for requests for the current user"),
                        @Tag(name = "Profile", description = "Endpoints for requests for other profiles"),
                        @Tag(name = "Articles", description = "Endpoints for requests for articles"),
                        @Tag(name = "Tags", description = "Endpoints for requests for tags")
                })
public class JaxrsApplication extends Application {

}
